project_id = "zaadxdryakogdyucdgqm"

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.resolve-menu]
verify_jwt = false

[functions.resolve-short-link]
verify_jwt = false
